### ISSUE TITLE
Return value is not shown when tender amount is greater than total bill amount

### ISSUE THREAD

**Issue by Pappustore** [oitcode/khajanchi#2]
Return value is not shown when tender amount is greater than total bill amount

**Comment by oitcode** [comment]
Issue is fixed.

Please check and close the issue.

**Comment by oitcode** [comment]
@Pappustore Please retest.

**Comment by oitcode** [comment]
@Pappustore Please update.

**Comment by oitcode** [comment]
Closing issue as fixed.
